spring:
    application:
        name: auth-server
    datasource:
        hikari:
            jdbc-url: jdbc:mysql://127.0.0.1:3306/security?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: 1111
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
        hibernate:
            ddl-auto: update
        open-in-view: false
        database: mysql
        show-sql: true
    sql:
        init:
            mode: always
            schema-locations: classpath:sql/schema.sql

server:
    port: 8081
